name: Tests and Linters

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Linters:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Install dependencies
        run: make deps
      - name: Run linters
        run: make lint

  Tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Run tests
        run: make test
      - name: Report stats
        run: make analyse

